### ISSUE TITLE
Feature Request: Slack (com.slack.Slack)

### ISSUE THREAD

**Issue by four43** [Frostbitten-jello/Skeuowaita#1]
Love the icons! Great work!

My existing icon: 
![image](https://user-images.githubusercontent.com/517006/212371156-55283b0d-c4be-4edd-abd1-ebbc8f3f8403.png)

**Comment by Frostbitten-jello** [comment]
@four43 thanks for the request! btw can you update the icon request and add actual names of icons in it as stated [here](https://github.com/Frostbitten-jello/Skeuowaita#how-to-find-the-actual-name-of-the-icon), will make the icon as soon as I can :)

**Comment by four43** [comment]
Look at you with the contributor guidelines already! Nice!

**Comment by Frostbitten-jello** [comment]
@four43 haha learning things slowly ;P, just how I also learned to pull before push ><

**Comment by Frostbitten-jello** [comment]
@four43 check the icon out!

**Comment by four43** [comment]
https://github.com/Frostbitten-jello/Skeuowaita/blob/main/scalable/apps/com.slack.Slack.svg

:tada: ! I love it - I love the inset parts of the logo are "3D" and raised too. Great job!
