### ISSUE TITLE
List of supported applications

### ISSUE THREAD

**Issue by forteller** [Frostbitten-jello/Skeuowaita#10]
Hi. Love your work!

It would be very useful with a list of all supported applications in the readme. Thanks! :)

**Comment by Frostbitten-jello** [comment]
thanks for the feedback! What purpose do you want the list for? can you elaborate?

**Comment by forteller** [comment]
I think it would be very useful for anyone who want to switch to this icon set, to see if all their most used apps are supported, and which they might need to request added before they feel comfortable using it. But it's more work for you, of course, so it's up to you. No worries :)

**Comment by Frostbitten-jello** [comment]
There is this [list of icons](https://github.com/Frostbitten-jello/Skeuowaita/issues/7#issue-1534235372) that people request, I don't delete entries from it. It is a good way IMO as it also shows icons that are currently in the pipeline. I will add the icons not present in it so we will have a complete list and mention about it in the Readme.

**Comment by Frostbitten-jello** [comment]
@forteller added the section to the readme with list of supported/currently worked on icons :)
