### ISSUE TITLE
How to update Icon set?

### ISSUE THREAD

**Issue by Hedronmx** [Frostbitten-jello/Skeuowaita#14]
Once installed how can I update the icons? Thank you

**Comment by Frostbitten-jello** [comment]
What desktop environment are you using?

**For gnome**, you can either run `gsettings set org.gnome.desktop.interface icon-theme 'Skeuowaita'` in the terminal

OR

you can install `gnome-tweaks` and go to `Appearance > Themes > Icons` and change the theme to `Skeuowaita` from the dropdown menu.

**Comment by Hedronmx** [comment]
> > Once installed how can I update the icons? Thank you
> 
> ```shell
> # user installation
> git -C ~/.local/share/icons/Skeuowaita pull
> 
> # or system installation
> sudo git -C /usr/share/icons/Skeuowaita pull
> ```

This works perfectly! Just beware for the read me. When you change the inherits property of the icon set, the pull command will fail. You would have to commit the changes
