### ISSUE TITLE
Request: Icon for Alacritty

### ISSUE THREAD

**Issue by Anderson0xFF** [Frostbitten-jello/Skeuowaita#16]
It would be really cool to add Alacritty to the list of icons, which is one of the most famous terminal emulators in the Unix world.
☺️☺️☺️☺️☺️
https://github.com/alacritty/alacritty

**Comment by Frostbitten-jello** [comment]
Can you tell the actual icon name as stated [here](https://github.com/Frostbitten-jello/Skeuowaita#how-to-find-the-actual-name-of-the-icon)
