### ISSUE TITLE
xfce: this icon theme has no cache file

### ISSUE THREAD

**Issue by o69mar** [Frostbitten-jello/Skeuowaita#2]
for some reason, xfce tells me that the icons have no cache file. it tells me to run gtk-update-icon-cache on /usr/share/icons/Skeuowaita. so i ran it on the terminal and gtk-update-icon-cache outputs "The generated cache was invalid." weird.

looks like i have to stick to papirus afterall. until this gets fixed. also is skeuowaita gonna be on the AUR soon?

**Comment by Frostbitten-jello** [comment]
@o69mar I saw that someone created a [package for AUR](https://aur.archlinux.org/packages/skeuowaita-git), not used it but it is there if u wanna give it a try.

**Comment by o69mar** [comment]
> @o69mar I saw that someone created a [package for AUR](https://aur.archlinux.org/packages/skeuowaita-git), not used it but it is there if u wanna give it a try. 

alright, I will try it

**Comment by four43** [comment]
Holy heck the Arch community is fast with the AURs

**Comment by Frostbitten-jello** [comment]
@o69mar did the AUR package fix your issue? or did you find any other solution?

**Comment by o69mar** [comment]
> @o69mar did the AUR package fix your issue? or did you find any other solution?
> 
> Also I made a new commit, can you check if it is working on your system?

it doesn't say the icon theme has no cache file, thanks

**Comment by Frostbitten-jello** [comment]
@o69mar that is awesome!! I had to add the breeze theme as dependency which fixed it :)
