### ISSUE TITLE
gtk-update-icon-cache seems to be finicky with whitespaces

### ISSUE THREAD

**Issue by purumamerin** [Frostbitten-jello/Skeuowaita#23]
gtk-update-icon-cache seems to be finicky with whitespaces, which results in generating a invalid cache file when cloning this repo directly on icons theme folder.

[Social Preview.png](https://github.com/Frostbitten-jello/Skeuowaita/blob/7bc64629b879b584fd2c2b93e9040b1081b3abd8/img/Social%20preview.png)
[Social Preview.svg](https://github.com/Frostbitten-jello/Skeuowaita/blob/7bc64629b879b584fd2c2b93e9040b1081b3abd8/img/Social%20preview.svg)
[Kdenlive org.kde.kdenlive.svg](https://github.com/Frostbitten-jello/Skeuowaita/blob/7bc64629b879b584fd2c2b93e9040b1081b3abd8/scalable/apps/Kdenlive%20org.kde.kdenlive.svg)

**Comment by Frostbitten-jello** [comment]
I think the issues are happening because of the icons made in inkscape are being handled by gnome in different ways. At least this is what someone told me when I had seen some artifacts with respect to the mesh gradient. I don't have much idea about it, so I don't think I can help. Sorry :(

**Comment by purumamerin** [comment]
Strange, by removing whitespaces from these filenames, gtk-update-icon-cache was able to generate the cache file. Sorry to bother you :)
