### ISSUE TITLE
[Request] - Thunderbird & Lutris

### ISSUE THREAD

**Issue by SubatomicCat** [Frostbitten-jello/Skeuowaita#26]
Hey, Thunderbird is getting a big UI update some time soon so I would like to request an icon for it; and since I am here, for Lutris as well:

Thunderbird: org.mozilla.Thunderbird
Lutris: net.lutris.Lutris

**Comment by Frostbitten-jello** [comment]
Hi, just added the icons, let me know what you think :)

have been busy so very very late lol
