### ISSUE TITLE
Request: Signal

### ISSUE THREAD

**Issue by RayJW** [Frostbitten-jello/Skeuowaita#27]
Welcome back! Love to see new icons, they look great! I would love to get an icon for the Signal desktop app :)

**Comment by Frostbitten-jello** [comment]
can you add the name of the icon file as mentioned [here](https://github.com/Frostbitten-jello/Skeuowaita#how-to-find-the-actual-name-of-the-icon) ... makes things a bit easier

**Comment by RayJW** [comment]
Sure! That would be `org.signal.Signal`.

**Comment by Frostbitten-jello** [comment]
Done :)

**Comment by RayJW** [comment]
Wow, that was fast, it looks amazing! Great work, I love it :)
