### ISSUE TITLE
Better icon for Gnome-Software

### ISSUE THREAD

**Issue by EinfachEli08** [Frostbitten-jello/Skeuowaita#9]
I have a new icon for the Gnome Software store icon and I’ve send you that in your post. It would be nice if you add that icon to your Icon Pack! You of course have to modify it a bit. So yea, hope th hear from you soon!

best wishes 
u/SomeRandoLameo

**Comment by Frostbitten-jello** [comment]
Hey thanks a lot for the request!!

can you share the link here? I got so many comments on the post that its kinda lost. I

**Comment by EinfachEli08** [comment]
Here you go!

https://svgshare.com/s/_QX

**Comment by Frostbitten-jello** [comment]
![image](https://user-images.githubusercontent.com/120028833/232273105-8177e7bb-b8b6-4d36-a4fc-250fe8c3d0a0.png)

**Comment by Frostbitten-jello** [comment]
@EinfachEli08 I worked on it and made some minor changes, also tried a few different ways but this one kinda looks better IMO, lemme know what you think :)

**Comment by EinfachEli08** [comment]
This looks gorgeous!

**Comment by Frostbitten-jello** [comment]
glad you like it, I actually ended up making it the main icon and moved the older icon to extras.
